// Generated by dia2code
#ifndef SERVER__ABSTRACTSERVICES__H
#define SERVER__ABSTRACTSERVICES__H

#include <string>

namespace server {

  /// class AbstractServices - 
  class AbstractServices {
    // Attributes
  protected:
    string pattern;
    // Operations
  public:
    AbstractServices (const std::string& pattern);
    ~AbstractServices ();
    const std::string& getPattern () const;
    void setPattern (const std::string& pattern);
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus put (Json::Value& out, const Json::Value in);
  };

};

#endif
