// Generated by dia2code
#ifndef RENDU__ANIMATEDTILE__H
#define RENDU__ANIMATEDTILE__H


namespace rendu {
  class Tile;
}

#include "Tile.h"

namespace rendu {

  /// class AnimatedTile - 
  class AnimatedTile : public rendu::Tile {
  };

};

#endif
