// Generated by dia2code
#ifndef RENDU__CHARACTERMAP__H
#define RENDU__CHARACTERMAP__H

#include "SFML/Graphics.hpp" 

namespace rendu {
  class Tile;
}

#include "Tile.h"

namespace rendu {

  /// class characterMap - 
  class characterMap : public rendu::Tile {
    // Operations
  public:
    sf::Sprite generateCharacter (sf::Sprite& sprite);
  };

};

#endif
