// Generated by dia2code
#ifndef RENDU__ELEMENTSPRITE__H
#define RENDU__ELEMENTSPRITE__H


namespace sf {
  class Sprite;
};
namespace state {
  class PositionObs;
}


namespace rendu {

  /// class ElementSprite - 
  class ElementSprite : public sf::Sprite, public state::PositionObs {
    // Operations
  public:
    virtual void notifyPosX (int x);
    virtual void notifyPosY (int y);
  };

};

#endif
