// Generated by dia2code
#ifndef RENDU__ELEMENTSPRITE__H
#define RENDU__ELEMENTSPRITE__H


namespace rendu {
  class PositionObs;
}

#include "PositionObs.h"

namespace rendu {

  /// class ElementSprite - 
  class ElementSprite : public rendu::PositionObs {
    // Operations
  public:
    void notifyPositionX (int x);
  };

};

#endif
