// Generated by dia2code
#ifndef RENDU__ELEMENTSPRITE__H
#define RENDU__ELEMENTSPRITE__H


namespace rendu {
  class Pont;
  class PositionObs;
}

#include "Pont.h"
#include "PositionObs.h"

namespace rendu {

  /// class ElementSprite - 
  class ElementSprite : public rendu::Pont, public rendu::PositionObs {
    // Operations
  public:
    ElementSprite ();
    void notifyPosX (int x);
    void notifyPosY (int y);
    ~ElementSprite ();
  };

};

#endif
