// Generated by dia2code
#ifndef RENDU__PONT__H
#define RENDU__PONT__H

#include "SFML/Graphics.hpp" 

namespace sf {
  class Sprite;
}


namespace rendu {

  /// class Pont - 
  class Pont : public sf::Sprite {
    // Attributes
  private:
    sf::Sprite sprite;
  };

};

#endif
