// Generated by dia2code
#ifndef RENDU__POSITIONOBS__H
#define RENDU__POSITIONOBS__H


namespace rendu {

  /// class PositionObs - 
  class PositionObs {
    // Operations
  public:
    virtual void notifyPosX (int x) = 0;
    virtual void notifyPosY (int y) = 0;
  };

};

#endif
