// Generated by dia2code
#ifndef RENDU__STATICTILE__H
#define RENDU__STATICTILE__H


namespace rendu {
  class Tile;
}

#include "Tile.h"

namespace rendu {

  /// class StaticTile - 
  class StaticTile : public rendu::Tile {
  };

};

#endif
