// Generated by dia2code
#ifndef RENDU__TILEMAP__H
#define RENDU__TILEMAP__H

#include <string>

namespace rendu {

  /// class TileMap - 
  class TileMap {
    // Operations
  public:
    bool load (const std::string& tileset, sf::Vector2u tileSize, const int* tiles, unsigned int width, unsigned int height);
  private:
    virtual void const draw (sf::RenderTarget& target, sf::RenderStates& states);
  };

};

#endif
