// Generated by dia2code
#ifndef RENDU__TILEMAP__H
#define RENDU__TILEMAP__H

#include "SFML/Graphics.hpp" 
#include <string>

namespace sf {
  class Drawable;
}


namespace rendu {

  /// class TileMap - 
  class TileMap : public sf::Drawable {
    // Attributes
  protected:
    sf::VertexArray m_verticles;
    sf::Texture m_tileset;
    // Operations
  public:
    bool load (const std::string& tileset, sf::Vector2u tileSize, const int* tiles, unsigned int width, unsigned int height);
  private:
    virtual void draw (sf::RenderTarget& target, sf::RenderStates& states) const;
  };

};

#endif
