// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H


namespace state {
  class Character;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class AttackCommand - 
  class AttackCommand : public engine::Command {
    // Attributes
  public:
    state::Character* attacker;
    state::Character* victim;
    // Operations
  public:
    AttackCommand (state::Character* attacker, state::Character* victim);
    void run ();
  };

};

#endif
