// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H


#include "state/Direction.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Operations
  public:
    void moveElement (state::Direction dir);
  };

};

#endif
