// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H


namespace state {
  class Character;
  class State;
}

#include "state/Direction.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Operations
  public:
    void moveElement (state::Direction dir, state::Character* character);
    void attack (state::Character* c, state::Character* d);
    void changeturns (state::State& s);
  };

};

#endif
