// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H


namespace engine {

  /// class Engine - 
  class Engine {
    // Operations
  public:
    void moveElement ();
  };

};

#endif
