// Generated by dia2code
#ifndef ENGINE__MOVECOMMAND__H
#define ENGINE__MOVECOMMAND__H


namespace state {
  class Character;
};
namespace engine {
  class Command;
}

#include "state/Direction.h"
#include "Command.h"

namespace engine {

  /// class MoveCommand - 
  class MoveCommand : public engine::Command {
    // Attributes
  public:
    state::Direction dir;
    state::Character* character;
    // Operations
  public:
    void run ();
    MoveCommand (state::Direction dir, state::Character* character);
    ~MoveCommand ();
  };

};

#endif
