// Generated by dia2code
#ifndef IA__IA__H
#define IA__IA__H


namespace state {
  class Character;
};
namespace engine {
  class Engine;
}

#include "engine/Engine.h"

namespace ia {

  /// class IA - 
  class IA {
    // Operations
  public:
    void IAExecute (state::Character* c, engine::Engine e);
  };

};

#endif
