// Generated by dia2code
#ifndef IA__IA__H
#define IA__IA__H


namespace engine {
  class Engine;
};
namespace state {
  class State;
}

#include "state/Direction.h"
#include "engine/Engine.h"
#include "state/State.h"

namespace ia {

  /// class IA - 
  class IA {
    // Operations
  public:
    state::Direction Execute (engine::Engine moteur, state::State etat);
  };

};

#endif
