// Generated by dia2code
#ifndef IA__IA__H
#define IA__IA__H

#include <vector>

namespace engine {
  class Engine;
};
namespace state {
  class State;
  class Character;
}

#include "state/Direction.h"
#include "engine/Engine.h"
#include "state/State.h"

namespace ia {

  /// class IA - 
  class IA {
    // Operations
  public:
    state::Direction ExecuteDumb (engine::Engine moteur, state::State etat);
    state::Direction ExecuteGroupAI (engine::Engine moteur, std::vector<state::Character*> group);
  };

};

#endif
