// Generated by dia2code
#ifndef IA__NODE__H
#define IA__NODE__H


namespace ia {

  /// class Node - 
  class Node {
    // Attributes
  public:
    int x;
    int y;
    float cout;
    std::pair<int,int> parent;
  };

};

#endif
