// Generated by dia2code
#ifndef STATE__AELEMENTFABRICATOR__H
#define STATE__AELEMENTFABRICATOR__H


namespace state {

  /// class AElementFabricator - 
  class AElementFabricator {
    // Attributes
  public:
     ;
    // Operations
  public:
    AElementFabricator ();
    virtual generate ();
  };

};

#endif
