// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H

#include <string>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Character - 
  class Character : public state::Element {
    // Attributes
  protected:
    int speed;
    int position;
    int strength;
    int xp;
    int level;
    int hitpoints;
    std::string name;
    // Operations
  public:
    Character ();
    bool const isCharacter ();
    int getSpeed ();
    void setSpeed (int speed);
    void setStrength (int strength);
    int getStrength ();
    void setXP (int xp);
    int getXP ();
    void attack ();
    ~Character ();
    int getHitPoints ();
    void setHitPoints (int hitPoints);
    std::string getName ( );
    void setName (std::string name);
    int getLevel ();
    void setLevel (int level);
  };

};

#endif
