// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Character - 
  class Character : public state::Element {
    // Attributes
  protected:
    int speed;
    int position;
    int strength;
    int xp;
    int level;
    int hitpoints;
    char name;
    // Operations
  public:
    Character ();
    bool const isCharacter ();
    int getSpeed ();
    void setSpeed (int speed);
    void setStrength (int strength);
    int getStrength ();
    void setXP (int xp);
    int getXP ();
    void attack ();
    ~Character ();
  };

};

#endif
