// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H

#include <string>

namespace state {
  class Element;
}

#include "Direction.h"
#include "Element.h"

namespace state {

  /// class Character - 
  class Character : public state::Element {
    // Associations
    // Attributes
  protected:
    int speed;
    int strength;
    int xp;
    int level;
    int hitpoints;
    std::string name;
    Direction direction;
    bool turn;
    int movecount;
    // Operations
  public:
    Character ();
    bool const isCharacter ();
    int getSpeed ();
    void setSpeed (int speed);
    void setStrength (int strength);
    int getStrength ();
    void setXP (int xp);
    int getXP ();
    void attack ();
    int getLevel ();
    int getHitPoints ();
    std::string getName ();
    /// 	
    /// @param level		(???) 
    void setLevel (int level);
    void setHitPoints (int hitpoints);
    void setName (std::string name);
    void setTurn (bool turn);
    void incMovecount ();
    void resetMovecount (int debug = 0);
    int getMovecount ();
    bool getTurn ();
    ~Character ();
  };

};

#endif
