// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H


namespace state {

  enum Direction {
    Up     = 0,
    Left     = 1,
    Down     = 2,
    Right     = 3
  };

};

#endif
