// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H

#include <vector>

namespace rendu {
  class PositionObs;
}

namespace state {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    int x;
    int y;
    std::vector<rendu::PositionObs*> obs;
    bool notifyMove;
    // Operations
  public:
    bool const isStatic ();
    int getX ();
    int getY ();
    void setX (int x);
    void setY (int y);
    Element ();
    void addPosObs (rendu::PositionObs* p);
  };

};

#endif
