// Generated by dia2code
#ifndef STATE__ELEMENTFABRICATOR__H
#define STATE__ELEMENTFABRICATOR__H


namespace state {
  class Element;
  class AElementFabricator;
}

#include "AElementFabricator.h"

namespace state {

  /// class ElementFabricator - 
  template <  class T,   typename Key>
  class ElementFabricator : public state::AElementFabricator {
    // Attributes
  public:
    Key key;
     kek;
    // Operations
  public:
    virtual Element* generate ();
  };

};

#endif
