// Generated by dia2code
#ifndef STATE__ELEMENTLIST__H
#define STATE__ELEMENTLIST__H

#include <vector>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class ElementList - 
  class ElementList {
    // Associations
    // Attributes
  public:
    std::vector<Element*> elements;
    // Operations
  public:
    ElementList (std::vector<Element*>  list);
    /// 	
    /// @param e		(???) 
    void AddElement (Element* e);
    void RemoveElement (Element* e);
    void clearlist ();
  };

};

#endif
