// Generated by dia2code
#ifndef STATE__ELEMENTLIST__H
#define STATE__ELEMENTLIST__H

#include <vector>

namespace state {
  class Element;
  class State;
  class ElementFabricator;
}

#include "ElementFabricator.h"
#include "Element.h"

namespace state {

  /// class ElementList - 
  class ElementList {
    // Associations
    // Attributes
  public:
    std::vector<Element*> elements;
    // Operations
  public:
    ElementList (State& state);
  };

};

#endif
