// Generated by dia2code
#ifndef STATE__ELEMENTFABRICATOR__H
#define STATE__ELEMENTFABRICATOR__H


namespace state {
  class Element;
}

namespace state {

  /// class ElementFabricator - 
  class ElementFabricator {
    // Operations
  public:
    virtual Element* generate ();
  };

};

#endif
