// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {

  /// class Element - 
  class Element {
    // Attributes
  public:
    int x;
    int y;
    // Operations
  public:
    bool const isStatic ();
  };

};

#endif
