// Generated by dia2code
#ifndef STATE__FACTORY__H
#define STATE__FACTORY__H

#include <string>
#include <map>
#include <memory>

namespace state {
  class Element;
  class ElementFabricator;
}

#include "ElementFabricator.h"

namespace state {

  /// class Factory - 
  class Factory : public state::ElementFabricator {
    // Attributes
  public:
    std::map<std::string, std::unique_ptr<ElementFabricator>> registry;
    // Operations
  public:
    virtual Element* generate (char key);
    void registerType (char key);
  };

};

#endif
