// Generated by dia2code
#ifndef STATE__FACTORY__H
#define STATE__FACTORY__H

#include <map>

namespace state {
  class Element;
  class Factory;
  class AElementFabricator;
}

#include "AElementFabricator.h"

namespace state {

  /// class Factory - 
  class Factory {
    // Associations
    // Attributes
  public:
    std::map<char,ElementFabricator> registry;
    // Operations
  public:
    virtual Element* generate (char key);
    void register (char key, Factory f);
  };

};

#endif
