// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H


namespace state {
  class StateObserver;
}

#include "StateObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
  };

};

#endif
