// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H


namespace state {
  class State;
  class StateObserver;
}

#include "State.h"
#include "StateObserver.h"

namespace state {

  /// class Observable - 
  class Observable : public state::State {
    // Associations
  };

};

#endif
