// Generated by dia2code
#ifndef STATE__POSITIONOBS__H
#define STATE__POSITIONOBS__H


namespace state {

  /// class PositionObs - 
  class PositionObs {
    // Operations
  public:
    virtual void notifyPosX (int x);
    virtual void notifyPosY (int y);
  };

};

#endif
