// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class StaticElement;
}

#include "SpaceTypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Space - 
  class Space : public state::StaticElement {
    // Associations
    // Operations
  public:
    bool const isSpace ();
    SpaceTypeId getSpaceTypeId ();
    void setSpaceTypeId (SpaceTypeId id);
  };

};

#endif
