// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class Static;
}

#include "Static.h"

namespace state {

  /// class Space - 
  class Space : public state::Static {
    // Operations
  public:
    bool const isSpace ();
  };

};

#endif
