// Generated by dia2code
#ifndef STATE__SPACETYPEID__H
#define STATE__SPACETYPEID__H


namespace state {

  enum SpaceTypeId {
    ChangeMap     = 1,
    CombatZone     = 2,
    NoCombatZone     = 3
  };

};

#endif
