// Generated by dia2code
#ifndef STATE__STATEEVENT__H
#define STATE__STATEEVENT__H


namespace state {
  class StateEventId;
}

#include "StateEventId.h"

namespace state {

  /// class StateEvent - 
  class StateEvent {
    // Associations
  };

};

#endif
