// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  /// class StateEventId - 
  class StateEventId {
    // Attributes
  public:
     LOADMAP;
  };

};

#endif
