// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>

namespace state {
  class Grid;
  class ElementList;
}

#include "Grid.h"
#include "ElementList.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  public:
    std::vector<int> level;
    // Operations
  public:
    State ();
    ~State ();
  };

};

#endif
