// Generated by dia2code
#ifndef STATE__STATEOBSERVER__H
#define STATE__STATEOBSERVER__H


namespace state {
  class StateEvent;
}

namespace state {

  /// class StateObserver - 
  class StateObserver {
    // Operations
  public:
    StateObserver ();
    void StateChanged (const StateEvent& e);
  };

};

#endif
