// Generated by dia2code
#ifndef STATE__WALL__H
#define STATE__WALL__H


namespace state {
  class StaticElement;
}

#include "WallTypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Wall - 
  class Wall : public state::StaticElement {
    // Associations
    // Operations
  public:
    Wall ();
    bool const isSpace ();
    WallTypeId const getWallTypeId ();
    void setWallTypeId (WallTypeId id);
  };

};

#endif
