// Generated by dia2code
#ifndef STATE__WALLTYPEID__H
#define STATE__WALLTYPEID__H


namespace state {

  enum WallTypeId {
    TopLeft     = 1,
    TopRight     = 2,
    BottomRight     = 3,
    BottomLeft     = 4,
    Horizontal     = 5,
    Vertical     = 6,
    Obstacle     = 7
  };

};

#endif
