// Generated by dia2code
#ifndef STATE__WALLTYPEID__H
#define STATE__WALLTYPEID__H


namespace state {

  enum WallTypeId {
    TopLeft,
    TopRight,
    BottomRight,
    BottomLeft
  };

};

#endif
