// Generated by dia2code
#ifndef CHARACTER__H
#define CHARACTER__H

/// class Character - 
class Character : public Element {
  // Attributes
protected:
   int speed;
   int position;
   int strength;
   int xp;
   int level;
   int movement_points;
   int action_points;
   Direction d;
  // Operations
public:
  Character ();
  bool const isCharacter ();
  TypeId const getTypeId ();
  int const getSpeed ();
  int const getPosition ();
  void setDirection (Direction d);
  void setSpeed (int s);
  CharacterStatus const getStatus ();
  void setStrength (int strenght);
  int const getStrength ();
  void setXP (int XP);
  int const getXP ();
  int const getLevel();
  void setLevel(int l);
};

#endif
