// Generated by dia2code
#ifndef CHARACTERSTATUS__H
#define CHARACTERSTATUS__H

/// class CharacterStatus - 
class CharacterStatus {
  // Associations
  // Attributes
public:
   YOURTURN;
   HISTURN;
   DEAD;
};

#endif
