// Generated by dia2code
#ifndef CHARACTER__H
#define CHARACTER__H

/// class Character - 
class Character {
  // Attributes
protected:
  int speed;
  int position;
  int strength;
  int xp;
  int level;
  int hitpoints;
  // Operations
public:
  Character ();
  bool const isCharacter ();
  int const getSpeed ();
  int const getPosition ();
  void setSpeed (int s);
  void setStrength ();
  const int getStrength ();
  void setXP ();
  int const getXP ();
  void attaquer ();
  ~Character ();
};

#endif
