// Generated by dia2code
#ifndef ELEMENTFACTORY__H
#define ELEMENTFACTORY__H

/// class ElementFactory - 
class ElementFactory {
  // Attributes
public:
   ;
  // Operations
public:
  ElementFactory ();
  Element* const newInstance (char id);
};

#endif
