// Generated by dia2code
#ifndef ELEMENTGRID__H
#define ELEMENTGRID__H

/// class ElementGrid - 
class ElementGrid : public ElementList {
  // Attributes
protected:
  int width;
  int height;
  // Operations
public:
  ElementGrid* const clone ();
  void copy ( other: const ElementGrid&);
  bool const hasCell (int i, int j);
  int const getWidth ();
  int const getHeight ();
  getCell (int i, int j);
};

#endif
