// Generated by dia2code
#ifndef MOVECOMMAND__H
#define MOVECOMMAND__H

/// class MoveCommand - 
class MoveCommand : public engine::Command {
  // Attributes
public:
  state::Direction dir;
  state::Character* character;
  // Operations
public:
  MoveCommand (state::Direction dir, state::Character* character);
};

#endif
