// Generated by dia2code
#ifndef OBSERVABLE__H
#define OBSERVABLE__H

/// class Observable - 
class Observable : public State {
  // Associations
  // Operations
public:
  void notifyObserver ();
};

#endif
