// Generated by dia2code
#ifndef SPACE__H
#define SPACE__H

/// class Space - 
class Space : public StaticElement {
  // Operations
public:
  Space (SpaceTypeId id);
  bool const isSpace ();
  TypeId const getTypeId ();
  Element* const clone ();
  bool const equals (const Element& other,  );
  SpaceTypeId const getSpaceTypeId ();
  void setSpaceTypeId (SpaceTypeId id);
  boolean isChangeMap ();
  SetTexture ();
};

#endif
