// Generated by dia2code
#ifndef __STATE__H
#define __STATE__H

#include "state/Element.h"
#include "state/Character.h"
#include "state/Static.h"
#include "state/WallTypeId.h"
#include "state/Wall.h"
#include "state/Space.h"
#endif
