// Generated by dia2code
#ifndef STATICELEMENT__H
#define STATICELEMENT__H

/// class StaticElement - 
class StaticElement : public Element {
  // Operations
public:
  bool const isStatic ();
  bool const isSpace ();
};

#endif
