// Generated by dia2code
#ifndef STATE__H
#define STATE__H

/// class State - 
class State {
  // Associations
  // Attributes
protected:
  ElementList chars;
  ElementGrid grid;
  int epoch;
  int epochRate;
  // Operations
public:
  State ();
  ~State ();
  State* const clone ();
  ElementGrid* const getGrid ();
  ElementList* const getList ();
  void setGrid ();
  void LoadLevel ();
};

#endif
