// Generated by dia2code
#ifndef WALLTYPEID__H
#define WALLTYPEID__H

/// class WallTypeId - 
class WallTypeId {
  // Associations
  // Attributes
public:
   BOTTOMLEFT;
   BOTTOMRIGHT;
   TOPLEFT;
   TOPRIGHT;
   HORIZONTAL;
   VERTICAL;
   DOODAD = 7;
};

#endif
